name: Deploy application to GCP App Engine

on: [push]
#  release:
#    types: [created]

env:
  GCP_PROJECT: ${{ secrets.PROJECT }}
  SA_EMAIL: ${{ secrets.GCP_EMAIL }}

jobs:
  setup-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}

    - name: Decrypt secrets
      run: ./.github/scripts/decrypt_secrets.sh
      env:
        DECRYPTION_PASSPHRASE: ${{ secrets.DECRYPTION_PASSPHRASE }}

    - run: |
        gcloud auth activate-service-account ${{ secrets.GCP_EMAIL }} --key-file=$HOME/secrets/service_account.json
        gcloud config set project ${{ secrets.PROJECT }}
        gcloud app deploy
